apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pgadmin-ingress
  namespace: sasf-qa
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
    - host: pgadmin.codeparce
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: pgadmin-service
                port:
                  number: 80
