apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: pgadmin-ingress
  namespace: sasf-qa
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`pgadmin.codeparce`)
      kind: Rule
      services:
        - name: pgadmin-service
          port: 80