apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-config-pvc
  namespace: codeparce-devops
spec:
  volumeName: gitlab-config-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-data-pvc
  namespace: codeparce-devops
spec:
  volumeName: gitlab-data-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
