apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-nfs-pvc
  namespace: codeparce-devops
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: "nfs"
