
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cluster-sa
  namespace: examples
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-role
  namespace: examples

rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["nodes", "pods","services"]
  verbs: ["get", "watch", "list"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-rb
subjects:
- kind: ServiceAccount
  name: cluster-sa # "name" is case sensitive
  namespace: examples

roleRef:
  # "roleRef" specifies the binding to a Role / ClusterRole
  kind: ClusterRole 
  name: cluster-role
  apiGroup: rbac.authorization.k8s.io

## Validalo con 
## kubectl auth can-i get secrets --as=system:serviceaccount:examples:github-arc-sa
