apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: blue-green-hpa
spec:
  # ¿A que va a escalar?
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: blue-green-deployment

  #Minimo y maximo de replicas
  minReplicas: 1
  maxReplicas: 3

  # metricas que va a evaluar  para escalar
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50

## para usar este manifest
## debes de tener instalado en el cluster
## Metrics server
## kubectl top pods